// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAdOMklaIXmrXTe_LmH8OGuPkTLCORcLc',
    appId: '1:832052160615:web:d554c951fec1e5b6718cc2',
    messagingSenderId: '832052160615',
    projectId: 'instatwo-e6170',
    authDomain: 'instatwo-e6170.firebaseapp.com',
    storageBucket: 'instatwo-e6170.appspot.com',
    measurementId: 'G-5EB3PGRCJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrOI5PiqBDOidAxu_fsUQ7YR_F797c_MI',
    appId: '1:832052160615:android:01c33190553b0b43718cc2',
    messagingSenderId: '832052160615',
    projectId: 'instatwo-e6170',
    storageBucket: 'instatwo-e6170.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhA7k2-93otqt-3CBWw-uhW0oSsUKoVFg',
    appId: '1:832052160615:ios:68a877d845ab58b6718cc2',
    messagingSenderId: '832052160615',
    projectId: 'instatwo-e6170',
    storageBucket: 'instatwo-e6170.appspot.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhA7k2-93otqt-3CBWw-uhW0oSsUKoVFg',
    appId: '1:832052160615:ios:da26718f007e57ca718cc2',
    messagingSenderId: '832052160615',
    projectId: 'instatwo-e6170',
    storageBucket: 'instatwo-e6170.appspot.com',
    iosBundleId: 'com.example.instagram.RunnerTests',
  );
}
