// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTNFGUcZYIRFbRM26VP799afZ68SX_puA',
    appId: '1:257455787498:web:d1195223840b4598f2f693',
    messagingSenderId: '257455787498',
    projectId: 'instagram-project-871da',
    authDomain: 'instagram-project-871da.firebaseapp.com',
    storageBucket: 'instagram-project-871da.appspot.com',
    measurementId: 'G-1JK8CZWGFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq7Sk-bFCy_v0s1G778NptPt2mnp44ak8',
    appId: '1:257455787498:android:48cd7a3b42eda970f2f693',
    messagingSenderId: '257455787498',
    projectId: 'instagram-project-871da',
    storageBucket: 'instagram-project-871da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKf9s-xJPD2Kpa_muq9x7KQHKWUUPlOos',
    appId: '1:257455787498:ios:f57f4b18b1969360f2f693',
    messagingSenderId: '257455787498',
    projectId: 'instagram-project-871da',
    storageBucket: 'instagram-project-871da.appspot.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKf9s-xJPD2Kpa_muq9x7KQHKWUUPlOos',
    appId: '1:257455787498:ios:6a56861bfa5aca95f2f693',
    messagingSenderId: '257455787498',
    projectId: 'instagram-project-871da',
    storageBucket: 'instagram-project-871da.appspot.com',
    iosBundleId: 'com.example.instagram.RunnerTests',
  );
}
